### ISSUE TITLE
[feat] 데이터 연동하면서 더 매끄러운 값 전달하기

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#112]
## 🐲 Description
워치에서 아이폰으로 데이터 전달하기

## 🧑‍💻 Todo
- [ ] 워치에서 전달하는 데이터 양식 다듬기
- [ ] CLLocation 어떻게 저장하는검니까

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by Damagucci-Juice** [comment]
완료된 이슈여서 닫습니다. 고생했어요 호제! @yunwkgus
