### ISSUE TITLE
[refactor] iOS 프로젝트 구조 개선

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#123]
## 🐲 Description
iOS 프로젝트 구조를 개선합니다.

## 🧑‍💻 Todo
- [ ] 월요일에 구찌와 논의.
- [ ] 프로젝트 구조 MVVM으로 변경.

## ✏️ ETC
- 현재 플로우 구조는 데이터를 읽기만 합니다.
- 따라서, MVVM이랑 같은 구조로 작동합니다.
- 조금 더 익숙한 MVVM으로 가는건 어떨까요?

**Comment by Damagucci-Juice** [comment]
이거는 좀 더 이야기 해볼까요? 제안해주셔서 고마워요 단! 
세션 중에 말씀을 잠깐 나누기는 했는데, 최종 결론을 내린 것 같지는 않아서요. 어떻게 하면 좋을까요?
