### ISSUE TITLE
[refactor] 구찌가 쏘아올린 워치 린트 수정 요청

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#144]
## 🐲 Description
제목이 내용입니다. 워치 코드에서 린트 수정하려합니다.

## 🧑‍💻 Todo
- [x] 린트 경고문 없애기

**Comment by imhotdogboy** [comment]
앗차차 iOS 코드도 구찌가 볼날이 올까요..?
