### ISSUE TITLE
[feat] 워치 BPM 애니메이션 수정

### ISSUE THREAD

**Issue by choiuyeong** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#20]
## 🐲 Description
워치 BPM 애니메이션 수정입니다.

## 🧑‍💻 Todo
- [ ] 워치 BPM 애니메이션 수정

## ✏️ ETC
저는 웨슬리입니다 -0-

**Comment by Damagucci-Juice** [comment]
이제 BPM 사용하지 않아서 닫습니다.
