### ISSUE TITLE
[fix] 소리 끄기 기능 켜도 소리 나오는 버그

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#242]
## 🐲 Description
작업 내용을 작성해 주세요.
메인 화면에서 소리를 끄면 노래가 꺼지는데, 여기서 다른 뷰로 들어갔다가 다시 나오면 노래가 들림

## 🧑‍💻 Todo
- [ ] 세부 사항을 작성해 주세요.

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by yunwkgus** [comment]
#288 해당 이슈에서 다루고 있어요!
