### ISSUE TITLE
[refactor] Localization

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#305]
## 🐲 Description
SoccerBeat Localization

## 🧑‍💻 Todo
- [ ] Localization 국가 선정 및 적용

**Comment by Damagucci-Juice** [comment]
`I18N`, `Constrains` 에 대해서 고민해 보면 좋을 것 같아요~

**Comment by Damagucci-Juice** [comment]
#319 와 겹쳐서 이건 닫을게요.
