### ISSUE TITLE
[fix] 배포용 프로비저닝 프로파일 수정

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#314]
## 🐲 Description
배포버전 프로비저닝 프로파일 수정

## 🧑‍💻 Todo
- [ ] adHoc 새로 import

**Comment by Damagucci-Juice** [comment]
@Henrykim1111 
같이 작업하고 완료하고 닫습니다.
