### ISSUE TITLE
[fix] ShareView에서 공유시 터지는 버그 수정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#321]
## 🐲 Description
작업 내용을 작성해 주세요.
- 스크린샷 캡쳐시, profileModel을 찾지 못해서 앱이 터집니다. 

## 🧑‍💻 Todo
- [x] profileModel을 참조하는 시점 파악
- [x] 수정

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by Damagucci-Juice** [comment]
캡쳐시 profileModel을 참조 못하는데 버그를 타고 들어가보니,  ProfileModel의 이미지를 가져오는 부분에서 문제가 발생

프로필 이미지를 설정한 상태에선 공유가 잘 나오는 모습
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/16ab5c5b-4c41-4438-84fd-512225c15d33)

문제점: 프로필에서 이미지를 선택한 경우엔 공유하기가 문제 없이 되는데, 이미지를 선택하지 않고 공유하기를 누르면 터지는 버그가 발생한다.

**Comment by Damagucci-Juice** [comment]
선택한 프로필 사진을 공란으로 비우는 기능이 존재하나요?

**Comment by yunwkgus** [comment]
답이 늦었네요 미안합니다. 선택한 프로필 사진 공란으로 비우는 기능이 여전히 필요하신가요? 올려주신 풀리퀘에서 해결해주신 것 같은데 감사합니다.
