### ISSUE TITLE
[HAPPY] GUCCI'S BIRTHDAY💙🎈🎈🎈

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#372]
## 🐲 Description
구룡포의 개발 장인, 구찌 (본명 장영진) 님의 생신을 축하드립니다. 
이 Issue는 사커비트가 앱스토어에서 사라지는 날(없음)까지 영구 박제입니다 !

## 🧑‍💻 Todo
- [x] 행복하기
- [x] 건강하기
- [ ] 개발 잘하기
- [ ] 사커비트 흥하기
- [x] 밥 잘먹기

## ✏️ ETC
구찌의 30대 인생 계획에 사커비트 포함 꼭 부탁드립니다. 
💙재무 설계 + 인생 상담 구룡포에서 절찬리 진행중!💙

**Comment by hyungminkimdev** [comment]
@Damagucci-Juice 아직 29살인데 벌써 30대 이야기 꺼내는거 어떻게 생각하시죠?

**Comment by hyungminkimdev** [comment]
ㅎㅎ 곧 따라 갑니다~ 생일축하합니다 영진쓰~

**Comment by Damagucci-Juice** [comment]
아웅 진쩌 감사해여 여러분 ㅠㅠ
일단 절부터 받으시지요. (_ _)

부족하지만 챙겨주셔서 감사하구, 더운 날만큼 열심히 코딩해볼게요.
앞으로도 저희 달려가보자구요~~!

헨리 미국에서도 힘내주시구, 호제도 화이팅이에요~~ 
감사해유 ~~ 

![image](https://github.com/user-attachments/assets/1d572363-1679-447d-973d-b6855eb35de4)

사진은 그냥 이뻐서 ㅎㅎ

**Comment by Damagucci-Juice** [comment]
> @Damagucci-Juice 아직 29살인데 벌써 30대 이야기 꺼내는거 어떻게 생각하시죠?

@Henrykim1111 아무래도 민감한 주제를 꺼내다니 혼..나야겠죠?

**Comment by yunwkgus** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ 사진 예뻐서가 좀 재미나네요 *^^*

**Comment by Damagucci-Juice** [comment]
내년 생일에 만나요 ~
