### ISSUE TITLE
[🍀Jose the 윤자현] HAPPY BIRTHDAY 🎉🥳🎂

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#454]
## 🐲 Description
윤호제 탄생일을 진심으로 축하합니다~~

## 🧑‍💻 Todo
- ✅ 밥잘먹기
- ✅ 부모님께 감사인사와 사랑한다 전하기
- ✅ 한 살 더 먹기
- ✅ 행복하기
- ✅ 생일 축하받기

**Comment by Damagucci-Juice** [comment]
![6E861CD5-9694-4605-B1C9-F2520136654E_1_105_c](https://github.com/user-attachments/assets/a770040e-465d-4599-8bf5-5cd943a9d675)

호제의 생일 축하하며 윤자현으로 3행시 가보겠습니다.

윤: 윤이나는 호기심을 가지고 살아가는
자: 자랑스런 호제의
현: 현재, 오늘 생일을 진심으로 축하합니다. 하하하하하하

**Comment by yunwkgus** [comment]
8ㅅ8 사랑하는 여러분 감사합니다 !! 꺄르르 너무 재미있는데요!!

**Comment by yunwkgus** [comment]
답례로 삼행시 갑니다

장: 장밋빛 미래를 함께하자! 
구: 구름이 몰려 와도 비가 세차게 쏟아져도! 
지: 지나갈 수 있어 우리가 함께 라면 ! 꺄르르르르

**Comment by yunwkgus** [comment]
김: 김치볶음밥을 함께 먹자~
헨: 헨리야 미국에서 돌아오면
니: 니 자리는 바로 여기야 사커비트 !!
