### ISSUE TITLE
[Search] Stationary 관련 권한 요청 위치 재검토

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#468]
## 🐲 Description
Stationary 관련 권한 요청 위치 재검토

## 🧑‍💻 Todo
- [ ] 세부 사항을 작성해 주세요.

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by hyungminkimdev** [comment]
조건문에서 stationary 상태이면 바로 알람이 뜨기 이전에, 먼저 운동을 시작했는지 한 번 확인하는 플래그가 있으면 좋을 것 같아요.
운동을 시작하기 전에 서 있는 상태에서 Start를 누르면 측정이 시작하자마자 정지 상태 알람이 뜨는 경우가 있더라구요!
