### ISSUE TITLE
[feat] iOS healthKit manager 구현

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#48]
## 🐲 Description
iOS healthKit manager 구현.

## 🧑‍💻 Todo
- [ ] iOS healthKit manager 구현

## ✏️ ETC

**Comment by Damagucci-Juice** [comment]
구현 완료해서 닫습니다. 수고하셨어요 단! @geee3
